[package]
name = "blackjack-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.1"
strum = "0.26.2"
strum_macros = "0.26.2"
